blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'posts#index'
  resources :posts, except: [:index] do
    resources :comments, shallow: true, only: %i[create destroy]
  end

  get '/password', to: 'users#edit_password', as: 'edit_password'
  post '/password', to: 'users#update_password', as: 'update_password'
  resources :users, only: %i[new create edit update]
  resource :session, only: %i[new create destroy]
end

blog_on_rails/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new

    can :manage, :all if user.is_admin?

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Post do |post|
      post.user == user # current_user
    end

    can :destroy, Comment do |comment|
      comment.user == user # current_user
    end

    can :crud, User, id: user.id
  end
end

blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(created_at: :DESC) }, dependent: :destroy

  # Title is required and unique
  validates :title, presence: true, uniqueness: true

  # Body needs to be present and 50 or more characters.
  validates :body, presence: true, length: { minimum: 50 }
end

blog_on_rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  validates :email, presence: true, uniqueness: true,
    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # where I got this regex - https://stackoverflow.com/questions/22993545/ruby-email-validation-with-regex
end

blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    redirect_to new_session_path, { status: 303, alert: 'Please Sign In or Sign Up' } unless user_signed_in?
  end
  helper_method :authenticate_user!

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user
end

blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new params.require(:comment).permit(:body)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), status: 303
    else
      @comments = @post.comments.order(created_at: :desc)
      render 'posts/show', status: 303
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    if can? :destroy, @comment
      @comment.destroy
      redirect_to post_path(@comment.post), status: 303
    else
      redirect_to root_path, { status: 303, alert: 'Not authorized' }
    end
  end
end

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @posts = Post.order(created_at: :DESC)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post), { status: 303, notice: 'Post created successfully' }
    else
      render :new, status: 303
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit; end

  def update
    if @post.update post_params
      redirect_to post_path(@post), { status: 303, notice: 'Post updated successfully' }
    else
      render :edit, status: 303
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, { status: 303, notice: 'Post deleted successfully' }
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user!
    redirect_to root_path, { status: 303, alert: 'Not authorized' } unless can? :crud, @post
  end
end

blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email params[:email]
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, status: 303
    else
      redirect_to new_session_path, { status: 303, alert: 'Email Password not found' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, status: 303
  end
end

blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update edit_password update_password]
  before_action :find_user, only: %i[edit update edit_password update_password]
  before_action :authorize_user!, only: %i[edit update edit_password update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, status: 303
    else
      render :new, status: 303
    end
  end

  def edit; end

  def update
    if @user&.update user_params.except(:password, :password_confirmation)
      redirect_to root_path, { status: 303, notice: 'User profile updated successfully' }
    else
      render :edit, status: 303
    end
  end

  def edit_password; end

  def update_password
    if params[:new_password] != params[:current_password]
      if params[:new_password] == params[:new_password_confirmation]
        if @user&.authenticate params[:current_password]
          if @user&.update password: params[:new_password], password_confirmation: params[:new_password_confirmation]
            redirect_to root_path, { status: 303, notice: 'Password updated successfully' }
          else
            flash.now[:alert] = @user.errors.full_messages.join(', ')
            render :edit_password, status: 303
          end
        else
          flash.now[:alert] = 'Current password does not match'
          render :edit_password, status: 303
        end
      else
        flash.now[:alert] = 'New password and new password confirmation does not match'
        render :edit_password, status: 303
      end
    else
      flash.now[:alert] = 'New password cannot be same as current password'
      render :edit_password, status: 303
    end
  end

  private

  def find_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def authorize_user!
    redirect_to root_path, { status: 303, alert: 'Not authorized' } unless can? :crud, @user
  end
end

blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= tag.header class: %w( header ) do %>
      <%= tag.nav class: %w( navbar navbar-expand bg-light ) do %>
        <%= link_to "Blog On Rails", root_path, class: "navbar-brand" %>
        <%= content_tag :ul, class: "navbar-nav" do %>
          <% if user_signed_in? %>
            <%= content_tag :li, class: "nav-item" do %>
              <%= link_to current_user.name, edit_user_path(current_user), class: "nav-link" %>
            <% end %>
            <%= content_tag :li, class: "nav-item" do %>
              <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "nav-link" %>
            <% end %>
          <% else %>
            <%= content_tag :li, class: "nav-item" do %>
              <%= link_to "Sign In", new_session_path, class: "nav-link" %>
            <% end %>
            <%= content_tag :li, class: "nav-item" do %>
              <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
            <% end %>
          <% end %>
          <%= content_tag :li, class: "nav-item" do %>
            <%= link_to "Home", root_path, class: "nav-link" %>
          <% end %>
          <%= content_tag :li, class: "nav-item" do %>
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    
    <% flash.each do |type, message| %>
      <div class="alert alert-primary" role="alert">
        <%= message %>
      </div>
    <% end %>

    <%= tag.main class: %w( main container.fluid ) do %>
      <%= yield %>
    <% end %>

  </body>
</html>

blog_on_rails/app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div class="form-group">
    <h5><%= form.label :title %></h5>
    <%= form.text_field :title, class: "form-control", required: "required" %>
    <% if @post&.errors&.where(:title)&.last&.type == :taken %>
      <p class="field_with_errors"><%= @post.errors.full_messages_for(:title).join(', ') %></p>
    <% end %>
  </div>
  <div class="form_group">
    <h5><%= form.label :body %></h5>
    <%= form.text_area :body, cols: 50, rows: 5, minLength: 50, class: "form-control", required: "required" %>
  </div>
  <%= form.submit class: "btn btn-outline-primary btn-lg" %>
<% end %>

blog_on_rails/app/views/posts/edit.html.erb
          <%= render "form" %>

blog_on_rails/app/views/posts/index.html.erb
        <%= tag.posts class: %w( posts card-deck ) do %>
          <% @posts.each do |post| %>
            <div class="card">
              <div class="card-body">
                <div class="card-title">
                  <h4><%= link_to post.title, post_path(post.id), class: "card-link" %></h4>
                </div>
                <div class="card-text"><%= post.body %><br>
                  <small class="text-muted">By <%= post.user&.name || "DELETED" %></small>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>

blog_on_rails/app/views/posts/new.html.erb
          <%= render "form" %>

blog_on_rails/app/views/posts/show.html.erb
        <div class="post card border-0">
          <div class="card-body">
            <h1 class="card-title"><%= @post.title %></h1>
            <p class="card-text"><%= @post.body %></p>
            <small class="text-muted"><p>Posted <%= time_ago_in_words(@post.updated_at) %> ago | By <%= @post.user&.name || "DELETED" %></p></small>
            <% if can? :crud, @post %>
              <%= link_to("Edit", edit_post_path(@post), class: "btn btn-outline-primary btn-md") %>
              <%= link_to("Delete", post_path(@post), data: { turbo_method: :delete }, class: "btn btn-outline-primary btn-md") %>
            <% end %>

            <%= form_with model: [@post, @comment] do |form| %>
              <% if @comment.errors.present? %>
                <p class="form-errors">
                  <%= @comment.errors.full_messages.join(", ") %>
                </p>
              <% end %>
              <div class="form_group">
                <h5><%= form.label :comment, for: :body %></h5>
                <%= form.text_area :body, cols: 50, rows: 3, placeholder: "What's on your mind?", class: "form-control", required: "required" %>
              </div>
              <%= form.submit "Submit", class: "btn btn-outline-primary btn-lg" %>
            <% end %>

            <%= tag.comments class: %w( comments ) do %>
              <% @post.comments.each do |comment| %>
                <div class="card border-0">
                  <div class="card-body">
                    <p class="card-text"><%= comment.body %></p>
                    <small class="text-muted">Commented <%= time_ago_in_words(comment.created_at) %> ago | By <%= comment.user&.name || "DELETED" %>
                    <% if can? :destroy, comment %>
                      •
                      <%= link_to("Delete", comment_path(comment), data: { turbo_method: :delete }, class: "card-link") %>
                    <% end %></small>
                  </div>
                </div>
              <% end %>
            <% end %>

          </div>
        </div>

blog_on_rails/app/views/users/edit.html.erb
      <h1 class="m-2">Update profile</h1>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <h5><%= f.label :name %></h5>
          <%= f.text_field :name, class: "form-control", required: :required %>
        </div>
        <div class="form-group">
          <h5><%= f.label :email %></h5>
          <%= f.email_field :email, class: "form-control", required: :required %>
          <% if @user&.errors&.where(:email) %>
            <p class="field_with_errors"><%= @user.errors.full_messages_for(:email).join(', ') %></p>
          <% end %>
        </div>
        <%= f.submit class: "btn btn-outline-primary btn-lg" %>
      <% end %>
      <div class="container m-0">
        <%= link_to "Change Password", edit_password_path, class: "text-decoration-none" %>
      </div>

blog_on_rails/app/views/users/edit_password.html.erb
<h1 class="m-2">Change Password</h1>
<%= form_with url: update_password_path, method: :post do |f| %>
  <div class="form-group">
    <h5><%= f.label :current_password %></h5>
    <%= f.password_field :current_password, class: "form-control", required: :required %>
  </div>
  <br>
  <div class="form-group">
    <h5><%= f.label :new_password %></h5>
    <%= f.password_field :new_password, class: "form-control", required: :required %>
  </div>
  <div class="form-group">
    <h5><%= f.label :new_password_confirmation %></h5>
    <%= f.password_field :new_password_confirmation, class: "form-control", required: :required %>
  </div>
  <%= f.submit "Update Password", class: "btn btn-outline-primary btn-lg" %>
<% end %>

blog_on_rails/app/views/users/new.html.erb
      <h1 class="m-2">Sign Up</h1>

      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <h5><%= f.label :name %></h5>
          <%= f.text_field :name, class: "form-control", required: :required %>
        </div>
        <div class="form-group">
          <h5><%= f.label :email %></h5>
          <%= f.email_field :email, class: "form-control", required: :required %>
          <% if @user&.errors&.where(:email) %>
            <p class="field_with_errors"><%= @user.errors.full_messages_for(:email).join(', ') %></p>
          <% end %>
        </div>
        <div class="form-group">
          <h5><%= f.label :password %></h5>
          <%= f.password_field :password, class: "form-control", required: :required %>
        </div>
        <div class="form-group">
          <h5><%= f.label :password_confirmation %></h5>
          <%= f.password_field :password_confirmation, class: "form-control", required: :required %>
        </div>
          <% if @user&.errors&.where(:password_confirmation) %>
            <p class="field_with_errors"><%= @user.errors.full_messages_for(:password_confirmation).join(', ') %></p>
          <% end %>
        <%= f.submit class: "btn btn-outline-primary btn-lg" %>
      <% end %> 